### ISSUE TITLE
Is uuid4r still needed?

### ISSUE THREAD

**Issue by Aqualon** [skaes/logjam_agent#31]
Hi, the code in https://github.com/skaes/logjam_agent/blob/master/lib/logjam_agent.rb#L208-L218 prefers `uuid4r.uuid(4)` over `SecureRandom.uuid`. I did some benchmark and SecureRandom is much faster than uuid4r.

```
Warming up --------------------------------------
              UUID4R     3.536k i/100ms
        SecureRandom    16.287k i/100ms
Calculating -------------------------------------
              UUID4R     37.250k (± 3.8%) i/s -    187.408k in   5.038382s
        SecureRandom    173.052k (± 5.5%) i/s -    879.498k in   5.098110s

Comparison:
        SecureRandom:   173051.9 i/s
              UUID4R:    37250.3 i/s - 4.65x  slower
```
Results from ruby 2.4.1, similar difference is in ruby 2.3.1, benchmark script used:

```
require 'benchmark/ips'
require 'securerandom'
require 'uuid4r'

Benchmark.ips do |bm|

  bm.report("UUID4R") do
    UUID4R::uuid(4)
  end

  bm.report("SecureRandom") do
    SecureRandom.uuid
  end

  bm.compare!
end
```

Additionally using `delete('-')` instead of `gsub('-','')` could speed up uuid generation by another 15%.

**Comment by skaes** [comment]
Uuid4r is not required, it is optional. Originally I have used version 1 uuids, but it turned out that ossp-uuid has an incomplete implementation of those.
